# Generated by Django 5.0.7 on 2024-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_food',
            field=models.CharField(max_length=100),
        ),
    ]
